version: '3.8'

services:
  php:
    build:
      context: ./docker/php
    volumes:
      - ./:/var/www/html
    depends_on:
      - database
    environment:
      DATABASE_URL: "mysql://app_user:app_password@database:3306/app_db"
      APP_ENV: dev

  nginx:
    image: nginx:alpine
    ports:
      - "9090:80"
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php

  database:
    image: mariadb:10.6
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: app_db
      MYSQL_USER: app_user
      MYSQL_PASSWORD: app_password
    ports:
      - "3307:3306"

  adminer:
    image: adminer
    ports:
      - "8091:8080"
    depends_on:
      - database

volumes:
  db_data: